language: node_js
node_js:
  - "5.11"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g angular-cli@latest

script:
  - ng build --prod --aot
  - npm run precache

after_success:
  - firebase use default
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
